### ISSUE TITLE
Does not work with react 16

### ISSUE THREAD

**Issue by ppong** [lavrton/react-konva#120] opened 2017-08-03 18:38 UTC
I was trying to update our app to the react 16-beta.2 and react knova is running into the following error. Any help would be appreciated.

ERROR in ./~/react-konva/src/react-konva.js
Module not found: Error: Can't resolve 'react/lib/React' in '.../react-konva/src'

ERROR in ./~/react-konva/src/react-konva.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactInstanceMap' in '.../react-konva/src'
 
ERROR in ./~/react-konva/src/react-konva.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactMultiChild' in '.../react-konva/src'
 
ERROR in ./~/react-konva/src/react-konva.js
Module not found: Error: Can't resolve 'react-dom/lib/ReactUpdates' in '.../react-konva/src'

**Comment by igorrmotta** [comment] 2017-09-18 02:06
got the same issue here...

**Comment by igorrmotta** [comment] 2017-09-18 02:28
I guess there is nothing much that can be done. This library is really old and the issue is coming from the way it imports react and react-dom.

```js
var React = require('react/lib/React');

var ReactInstanceMap = require('react-dom/lib/ReactInstanceMap');
var ReactMultiChild = require('react-dom/lib/ReactMultiChild');
var ReactUpdates = require('react-dom/lib/ReactUpdates');
```

**Comment by lavrton** [comment] 2017-09-18 07:32
I will clarify current situation.

`react-konva` depends on some `React` private internals. There is no way to implement `react-konva` with using public API only (actually there is a way, but VERY VERY slow).

I am happy to update `react-konva` for support of `React` v16. But v16 has a lot of internal changes (new Fiber reconciler). With v16, we can't use old private API and I don't see a way to use new private API.

But I am tracking status of Fiber API here: https://github.com/facebook/react/issues/9103
As soon as I will have more info, I will update `react-konva`.

**Comment by ppong** [comment] 2017-09-29 03:36
Hey @lavrton, just wondering if you had a chance to take a look at the recently released react v16. Thanks!

**Comment by lavrton** [comment] 2017-09-29 07:44
@ppong I am waiting for this issue to be resolved: https://github.com/facebook/react/pull/10758
Then we can update `react-konva` for react v16.

**Comment by MichaelSavin** [comment] 2017-10-11 19:03
![image](https://user-images.githubusercontent.com/1640229/31460764-d618085e-aee0-11e7-97f6-2509f559b1f6.png)

**Comment by ngocdaothanh** [comment] 2017-10-14 21:48
@lavrton https://github.com/facebook/react/pull/10758 has been merged. Can you update react-konva for react v16?

**Comment by Flydiverny** [comment] 2017-10-15 10:03
Give him some time, I'm sure he's looking into it when he's available to, as he already expressed that he will. I also figure he'd need some time to figure out and rewrite stuff as react-konva can't depend on no longer existing private internals. Yes, the new reconciler package has been merged. If you are eager to get react-konva have a go at it and make a PR!

**Comment by lavrton** [comment] 2017-10-16 06:35
Current status. "React Reconciler Package" PR is merged. But `react-reconciler` package is not released yet in npm (just empty v0). As soon as it will be released I will start work with it.

Stay tuned and show your love. 🙌

**Comment by lavrton** [comment] 2017-11-03 05:27
`react-reconciler` is released.
Support for v16 is almost finished. All tests are green. 😻
Now I am going to test `react-konva` with the real app.
Also, I am going to release beta version. So you can test as well.

**Comment by programbo** [comment] 2017-11-03 05:35
Great timing!

**Comment by mattblackdev** [comment] 2017-11-03 06:04
Excellent! Now I can resume my plan to take over the world! MUAHAHAHA💥

**Comment by lavrton** [comment] 2017-11-04 02:09
Published beta version. You can try with:
```bash
npm install react@16.1.0-beta react-dom@16.1.0-beta react-konva@1.5.5-beta
```

I am going to make a master release when react v16.1.0 is out.

**Comment by samkit** [comment] 2017-11-04 09:53
Awesome work! Thanks.

A small glitch, for some reason on android-chrome onClick is not working. But I am still using react 16.0.0, hope that is not the issue here.

**Comment by cesardeazevedo** [comment] 2017-11-05 01:53
@lavrton I just did i try on my project, and everything is working perfectly, thanks for your effort.

**Comment by germanow** [comment] 2017-11-08 15:05
@lavrton add konva package in install command

```
npm install react@16.1.0-beta react-dom@16.1.0-beta react-konva@1.5.5-beta konva
```

**Comment by lavrton** [comment] 2017-11-10 05:59
I made a release `1.6.2`. It should work ok with React `v16`.

**Closed by lavrton** 2017-11-10 05:59 UTC
