### ISSUE TITLE
Error when building with Webpack 2.5: "Module not found: Error: Can't resolve 'canvas'

### ISSUE THREAD

**Issue by ay5000** [lavrton/react-konva#102] opened 2017-05-26 13:50 UTC
I am running into a webpack error with react-konva 1.1.3 and webpack 2.5:

ERROR in ./~/konva/konva.js

Module not found: Error: Can't resolve 'canvas' in '/******/node_modules/konva'

 @ ./~/konva/konva.js 251:19-36
 @ ./~/react-konva/src/react-konva.js
 @ ./assets/js/index.js

Thanks.

**Comment by lavrton** [comment] 2017-05-27 14:53
@ay5000 I have webpack `2.5.1` and I don't see any error. All works fine.
Can you create a demo repo?
Do you install `konva` as node module?

**Comment by andrew-luminal** [comment] 2017-06-13 04:02
@ay5000 We had the same issue -- webpack searches for dependencies before the code is run, so it doesn't realize that the `require('canvas')` call from `konva` (not `react-konva`) is unnecessary for a browser environment. It'll also give you that error for `jsdom`. Easy 1 line fix to your webpack config: 

```
plugins: [
   new webpack.IgnorePlugin(/canvas|jsdom/, /konva/)
]
```

**Comment by lavrton** [comment] 2017-06-13 05:13
It is very strange that it doesn't realize that that code is unnecessary for a browser. Because it is defined in `package.json`.

**Comment by veralex** [comment] 2017-06-14 09:29
@lavrton I have the same issue as @ay5000 . The code given by adrew-luminal did't work for me. What could be the problem?

**Comment by lavrton** [comment] 2017-06-14 10:19
I can help. But I need reproducible repo. Where I can `npm install` and `npm run build` and see the problem.

**Comment by veralex** [comment] 2017-06-14 16:05
Well, I found the reason, and the reason is AspNetCore SPA. I use AspNet SPA + Webpack + React + Redux stack. The problem is that AspNetCore can't prerender the library using 'canvas' on the server side (libraries using 'window' won't work either). So I decided to turn off aspnet-prerendering option. It seems that Microsoft uses their own JS engine not compatible with V8.

**Comment by janus-reith** [comment] 2017-07-22 12:27
I have the same issue on meteor:
Unable to resolve some modules:
  "canvas" in
  [....]

the dev server still works, but building fails.

**Comment by jthrilly** [comment] 2017-10-09 13:53
We have this issue, too, but this time when using the electron-renderer webpack target.

**Comment by lavrton** [comment] 2017-10-11 08:30
Should be resolved with the last version of Konva `v1.7.1`

**Closed by lavrton** 2017-10-11 08:30 UTC

**Comment by OKNoah** [comment] 2018-07-01 21:32
Sorry if this is the wrong issue, but I've wondered if there anyway Konva can do server-side rendering? There is `buildpack-cairo`, which I just realized my acquaintance @mojodna made. Could that make it possible to render konva canvas elements on the server? I have used `cairo` to render `canvas` on the server, but not output to react/HTML. If there are `window` specific requirements, what would be the chances of refactoring to render the initial canvas elements and then add the listeners? Just curious as it might be worth my trouble if I can find the time.

Or perhaps my premise is faulty and it should work?

**Comment by lavrton** [comment] 2018-07-02 02:55
@OKNoah no server-side rendering. `Konva` is drawing on `<canvas>`. We can not send canvas element with some drawing from the server.

**Comment by OKNoah** [comment] 2018-07-02 04:52
@lavrton Right. Currently I do in my render function

```jsx
if (typeof window !== 'undefined') {
  const Konva = require('react-konva')

  return (<Konva.Rect .... />)
}

return null
```

Maybe that's not necessary? But if it is, could we at least send this along as SSR'd:

```html
<canvas width="1132" height="748" style="padding: 0px; margin: 0px; border: 0px; background-color: transparent; position: absolute; top: 0px; left: 0px; width: 566px; height: 374px; background-position: initial initial; background-repeat: initial initial;"></canvas>
```

Then we don't have a flash of canvas elements loading after page load (drawn on or not). Of course this is also achievable by just putting a div of the same size and shape, while that would require redrawing and a small performance hit.

I'm just wondering. If React-Konva does need `window` as I assumed, I could look into doing a PR like this myself.

Maybe server-side could even generate an image, make it a png, and load it under a transparent canvas element on initial load? Pardon my ignorance if I'm way off.

**Comment by lavrton** [comment] 2018-07-02 05:00
Generating png and returning it instead of a canvas is a very interesting idea. 
Personally, I don't use SSR with `react-konva`, so I don't know possible use cases.

Please create another issue with your requirements and suggestions. I am happy to apply related PR.

**Comment by stephenasuncionDEV** [comment] 2023-08-02 04:53
Still experiencing with nextjs

**Comment by lavrton** [comment] 2023-08-07 00:14
@stephenasuncionDEV did you look here  https://github.com/konvajs/react-konva#usage-with-nextjs?

**Comment by dendrofen** [comment] 2023-11-29 18:27
@lavrton It seems issue happens once again, it should be connected with nextjs updates (changing of dynamic function)

**Comment by dev-fredericfox** [comment] 2024-03-27 10:59
Still an issue in 14.1.3...

**Comment by GVAmaresh** [comment] 2024-09-22 08:43
I've tried adding the following configuration in `next.config.mjs` to resolve the canvas-related issue:
```
export default {
  webpack: (config) => {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      canvas: false,
    };
    return config;
  },
};
```
---
Name: Konva compatibility issue with NextJS and TypeScript
Issue: Module not found: './canvas'
Solution: I am instructing Webpack to neglect the canvas module in the final bundle. 
---

## Expected Behavior
The Konva components should render correctly without any errors or issues.

## Actual Behavior
The application throws errors related to Konva nodes not being recognized and issues with rendering certain components. Specific error messages include:
- `Konva has no node with the type source. Group will be used instead.`
- `Text components are not supported for now in ReactKonva.`
- `Cannot read properties of undefined (reading 'getParent')`

The above errors encountered in the application regarding Konva, Text, getParent issues can be addressed through research and tailored solutions as I have successfully implemented solutions that work effectively for my application

## Environment
- NextJS version: [e.g., 13.0.0]
- TypeScript version: [e.g., 4.8.4]
- Konva version: [e.g., 8.3.14]
- react-konva version: [e.g., 18.2.0]

**Comment by lavrton** [comment] 2025-09-05 12:52
A little note: from `konva@10.0.0`, `react-konva` inside `next.js` should work without any configuration and without dynamic imports.
